#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Ben Jarvis
# SPDX-License-Identifier: LGPL-2.1-only
"""Generate peer-controlled transport pressure programs from Quint."""
import json
from pathlib import Path
import subprocess
import sys

OPS = 'Reset Connect Queue Hold Prefix Drain Finish Close PeerClose'.split()
FIELDS = 'live finishing take queued read drained'.split()


def emit(traces, output):
    rows, seen, witnesses = [], set(), set()
    for trace in traces:
        held = partial = False
        for state in json.loads(trace.read_text())['states']:
            op, s = state['op'], state['s']
            if op not in OPS or set(s) != set(FIELDS):
                raise ValueError('Unexpected backpressure model schema')
            if op in ('Reset', 'Connect'):
                held = partial = False
            held |= op == 'Hold'
            partial |= op == 'Prefix'
            if held and partial and op in ('Drain', 'Close', 'PeerClose'):
                witnesses.add((s['take'], op))
            def integer(value):
                return int(value['#bigint']) if isinstance(value, dict) else int(value)
            rows.append('  {pressure_' + op + ', ' + ', '.join(str(integer(s[k])) for k in FIELDS) + '},')
            seen.add(op)
    required = {(False, 'Drain'), (True, 'Drain'), (True, 'Close'), (False, 'PeerClose')}
    if seen != set(OPS) or not required <= witnesses:
        raise ValueError('Missing backpressure/partial-completion outcomes')
    output.write_text('/* Generated by Quint; do not edit. */\n#pragma once\n'
                      + 'enum { ' + ', '.join('pressure_' + op for op in OPS) + ' };\n'
                      + 'struct pressure_step { int op, ' + ', '.join(FIELDS) + '; };\n'
                      + 'static const struct pressure_step pressure_steps[] = {\n' + '\n'.join(rows) + '\n};\n')
    print(f'Backpressure: {len(traces)} traces, {len(rows)} operations, required outcomes present')


def main():
    quint, source, work, output = sys.argv[1:]
    work = Path(work)
    work.mkdir(parents=True, exist_ok=True)
    for old in work.glob('pressure-*.itf.json'):
        old.unlink()
    model = str(Path(source) / 'backpressure.qnt')
    subprocess.run([quint, 'test', '--backend=typescript', model, '--seed=827', '--verbosity=0',
                    '--out-itf=' + str(work / 'pressure-test-{test}-{seq}.itf.json')], check=True)
    subprocess.run([quint, 'run', '--backend=typescript', model, '--seed=827', '--verbosity=0',
                    '--max-steps=16', '--max-samples=4', '--n-traces=4', '--invariant=inv',
                    '--out-itf=' + str(work / 'pressure-random-{seq}.itf.json')], check=True)
    emit(sorted(work.glob('pressure-*.itf.json')), Path(output))


if __name__ == '__main__':
    main()
