#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Ben Jarvis
# SPDX-License-Identifier: LGPL-2.1-only
"""Generate fragmented datagram programs from Quint."""
import json
from pathlib import Path
import subprocess
import sys

OPS = 'Reset Connect Queue Hold Drain Close PeerClose CancelPrefix'.split()
FIELDS = 'live queued drained fragments take prefix'.split()


def emit(traces, output):
    rows, seen, shapes, outcomes = [], set(), set(), set()
    for trace in traces:
        for state in json.loads(trace.read_text())['states']:
            op, s = state['op'], state['s']
            if op not in OPS or set(s) != set(FIELDS):
                raise ValueError('Unexpected datagram model schema')
            def integer(value):
                return int(value['#bigint']) if isinstance(value, dict) else int(value)
            s = {k: integer(v) for k, v in s.items()}
            rows.append('  {datagram_' + op + ', ' + ', '.join(str(s[k]) for k in FIELDS) + '},')
            seen.add(op)
            if op == 'Queue':
                shapes.add((s['fragments'], s['take']))
            if op == 'CancelPrefix':
                outcomes.add(s['prefix'])
    if seen != set(OPS) or not {(1, 0), (4, 1), (5, 0), (65, 0), (65, 1)} <= shapes or outcomes != {1, 7}:
        raise ValueError('Missing fragmentation/ownership/cancellation witnesses')
    output.write_text('/* Generated by Quint; do not edit. */\n#pragma once\n'
                      + 'enum { ' + ', '.join('datagram_' + op for op in OPS) + ' };\n'
                      + 'struct datagram_step { int op, ' + ', '.join(FIELDS) + '; };\n'
                      + 'static const struct datagram_step datagram_steps[] = {\n' + '\n'.join(rows) + '\n};\n')
    print(f'Datagram boundaries: {len(traces)} traces, {len(rows)} operations, required outcomes present')


def main():
    quint, source, work, output = sys.argv[1:]
    work = Path(work)
    work.mkdir(parents=True, exist_ok=True)
    for old in work.glob('datagram-*.itf.json'):
        old.unlink()
    model = str(Path(source) / 'datagram_boundary.qnt')
    subprocess.run([quint, 'test', '--backend=typescript', model, '--seed=827', '--verbosity=0',
                    '--out-itf=' + str(work / 'datagram-test-{test}-{seq}.itf.json')], check=True)
    subprocess.run([quint, 'run', '--backend=typescript', model, '--seed=827', '--verbosity=0',
                    '--max-steps=16', '--max-samples=4', '--n-traces=4', '--invariant=inv',
                    '--out-itf=' + str(work / 'datagram-random-{seq}.itf.json')], check=True)
    emit(sorted(work.glob('datagram-*.itf.json')), Path(output))


if __name__ == '__main__':
    main()
