# SPDX-FileCopyrightText: 2025 Ben Jarvis
#
# SPDX-License-Identifier: Unlicense

version: 2
updates:
  - package-ecosystem: bundler
    directory: /docs
    schedule:
      interval: daily
    allow:
      - dependency-type: direct
