# SPDX-FileCopyrightText: 2026 Ben Jarvis
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by scripts/mbt_configurations.py; do not edit.
set(MBT_CONFIG_PROFILES pair00 pair01 pair02 pair03 pair04 pair05 pair06 pair07 pair08)
