// SPDX-FileCopyrightText: 2026 Ben Jarvis
// SPDX-License-Identifier: LGPL-2.1-only
// Generated by scripts/mbt_configurations.py; do not edit.
#pragma once
struct mbt_config_profile {
    const char  *name;
    unsigned int buffer_size;
    unsigned int slab_size;
    unsigned int iovec_ring_size;
    unsigned int dgram_ring_size;
    unsigned int rdma_request_ring_size;
    unsigned int max_datagram_batch;
    unsigned int max_poll_fd;
    unsigned int preallocate_threads;
};
/* *INDENT-OFF* */
static const struct mbt_config_profile mbt_config_profiles[] = {
    { "pair00", 32768, 131072, 4, 4, 4, 1, 1, 4 },
    { "pair01", 32768, 1048576, 32, 32, 32, 16, 16, 0 },
    { "pair02", 65536, 1048576, 4, 4, 4, 16, 16, 1 },
    { "pair03", 65536, 1048576, 32, 32, 32, 1, 1, 1 },
    { "pair04", 32768, 131072, 4, 32, 32, 16, 16, 4 },
    { "pair05", 32768, 131072, 32, 4, 4, 1, 1, 0 },
    { "pair06", 65536, 1048576, 32, 4, 32, 1, 16, 4 },
    { "pair07", 32768, 131072, 4, 32, 4, 16, 1, 1 },
    { "pair08", 65536, 1048576, 4, 4, 4, 1, 1, 0 },
};
/* *INDENT-ON* */
