#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Ben Jarvis
# SPDX-License-Identifier: LGPL-2.1-only
"""Deterministic, constrained pair coverage for native core MBT startup settings.

The selected rows are shared by CMake and the C interpreter. No randomness or
third-party solver is needed; ties are resolved by manifest order. Constraints
describe this replay's supported inputs, not validation promised by libevpl.
"""
import argparse
import itertools
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'src/core/tests/config_profiles.json'


def valid(row):
    return (row['buffer_size'] >= 32768
            and row['slab_size'] >= 4 * row['buffer_size']
            and row['slab_size'] % row['buffer_size'] == 0
            and all(row[k] >= 2 and row[k] & (row[k] - 1) == 0
                    for k in ('iovec_ring_size', 'dgram_ring_size', 'rdma_request_ring_size')))


def pairs(row):
    return frozenset((a, row[a], b, row[b]) for a, b in itertools.combinations(row, 2))


def configurations(manifest=None):
    spec = manifest or json.loads(MANIFEST.read_text())
    factors = spec['factors']
    candidates = [dict(zip(factors, values))
                  for values in itertools.product(*factors.values())]
    candidates = [row for row in candidates if valid(row)]
    if not candidates:
        raise ValueError('No valid MBT configurations')
    obligations = set().union(*(pairs(row) for row in candidates))
    remaining = obligations.copy()
    selected = []
    # Keep a deliberately pressured configuration, independent of greedy ties.
    seed = spec['stress']
    if seed not in candidates:
        raise ValueError('Stress configuration is not a valid candidate')
    while remaining:
        row = seed if not selected else max(candidates, key=lambda r: len(pairs(r) & remaining))
        selected.append(row)
        remaining.difference_update(pairs(row))
    return selected, obligations


def config_api(root=ROOT, libfabric=True):
    """Discover declarations so a newly added accessor cannot silently escape."""
    names = set()
    for path in [*Path(root).glob('include/evpl/*.h'), Path(root) / 'src/core/evpl.h']:
        source = re.sub(r'/\*.*?\*/|//[^\n]*', '', path.read_text(), flags=re.S)
        for declaration in re.findall(r'EVPL_API\s+([^;]+);', source):
            names.update(re.findall(r'\b(evpl_(?:(?:global|thread)_config_(?:set|get)_\w+|config_rpc2_max_message_size|get_slab_size))\s*\(', declaration))
    if not libfabric:
        names.discard('evpl_global_config_set_libfabric_external_domain')
    return names


def render():
    rows, obligations = configurations()
    fields = list(rows[0])
    license_c = '// SPDX-FileCopyrightText: 2026 Ben Jarvis\n// SPDX-' + 'License-Identifier: LGPL-2.1-only\n'
    header = license_c + '// Generated by scripts/mbt_configurations.py; do not edit.\n#pragma once\n'
    header += 'struct mbt_config_profile {\n    const char  *name;\n'
    header += ''.join(f'    unsigned int {field};\n' for field in fields)
    header += '};\n/* *INDENT-OFF* */\nstatic const struct mbt_config_profile mbt_config_profiles[] = {\n'
    header += ''.join('    { "pair%02d", %s },\n' % (i, ', '.join(str(r[f]) for f in fields))
                      for i, r in enumerate(rows))
    header += '};\n/* *INDENT-ON* */\n'
    cmake = '# SPDX-FileCopyrightText: 2026 Ben Jarvis\n# SPDX-' + 'License-Identifier: LGPL-2.1-only\n'
    cmake += '# Generated by scripts/mbt_configurations.py; do not edit.\n'
    cmake += 'set(MBT_CONFIG_PROFILES ' + ' '.join(f'pair{i:02d}' for i in range(len(rows))) + ')\n'
    return {'config_profiles.h': header, 'config_profiles.cmake': cmake}, len(obligations)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    outputs, count = render()
    for name, contents in outputs.items():
        path = MANIFEST.parent / name
        if args.check:
            if path.read_text() != contents:
                parser.error(f'{path} is stale; run scripts/mbt_configurations.py')
        else:
            path.write_text(contents)
    print(f'{len(configurations()[0])} configurations cover {count} valid value pairs')


if __name__ == '__main__':
    main()
